DROP TABLE user_login;

ALTER TABLE SCHEDULE
MODIFY COLUMN DAYOFWEEK INT UNSIGNED;

UPDATE SCHEDULE
SET DAYOFWEEK = CASE
    WHEN DAYOFWEEK = 'Monday' THEN 1
    WHEN DAYOFWEEK = 'Tuesday' THEN 2
    WHEN DAYOFWEEK = 'Wednesday' THEN 4
    WHEN DAYOFWEEK = 'Thursday' THEN 8
    WHEN DAYOFWEEK = 'Friday' THEN 16
    WHEN DAYOFWEEK = 'Saturday' THEN 32
    WHEN DAYOFWEEK = 'Sunday' THEN 64
    ELSE 0
END;

SELECT
  CONCAT_WS(', ',
    CASE WHEN (DAYOFWEEK & 1) <> 0 THEN 'Monday' ELSE NULL END,
    CASE WHEN (DAYOFWEEK & 2) <> 0 THEN 'Tuesday' ELSE NULL END,
    CASE WHEN (DAYOFWEEK & 4) <> 0 THEN 'Wednesday' ELSE NULL END,
    CASE WHEN (DAYOFWEEK & 8) <> 0 THEN 'Thursday' ELSE NULL END,
    CASE WHEN (DAYOFWEEK & 16) <> 0 THEN 'Friday' ELSE NULL END,
    CASE WHEN (DAYOFWEEK & 32) <> 0 THEN 'Saturday' ELSE NULL END,
    CASE WHEN (DAYOFWEEK & 64) <> 0 THEN 'Sunday' ELSE NULL END
  ) AS DaysString
FROM
  SCHEDULE;
  
ALTER TABLE SCHEDULE
DROP COLUMN DAYOFWEEK;
